// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Card: typeof import("./src/components/Card.vue")["default"];
    CForm: typeof import("./src/components/CForm.vue")["default"];
    CTable: typeof import("./src/components/CTable.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElSpace: typeof import("element-plus/es")["ElSpace"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    EmptyBlock: typeof import("./src/components/EmptyBlock.vue")["default"];
    IMdiFormatIndentDecrease: typeof import("~icons/mdi/format-indent-decrease")["default"];
    IMdiFullscreen: typeof import("~icons/mdi/fullscreen")["default"];
    IMdiFullscreenExit: typeof import("~icons/mdi/fullscreen-exit")["default"];
    IMdiGoogleTranslate: typeof import("~icons/mdi/google-translate")["default"];
    IMdiWeatherNight: typeof import("~icons/mdi/weather-night")["default"];
    IMdiWhiteBalanceSunny: typeof import("~icons/mdi/white-balance-sunny")["default"];
    Panel: typeof import("./src/components/Panel.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchFilter: typeof import("./src/components/SearchFilter.vue")["default"];
    VeeValidateError: typeof import("./src/components/VeeValidateError.vue")["default"];
    WangEditor: typeof import("./src/components/WangEditor.vue")["default"];
  }
}

export {};
