// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Card: typeof import("./src/components/Card.vue")["default"];
    CForm: typeof import("./src/components/CForm.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopconfirm: typeof import("element-plus/es")["ElPopconfirm"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSpace: typeof import("element-plus/es")["ElSpace"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    IMdiFormatIndentDecrease: typeof import("~icons/mdi/format-indent-decrease")["default"];
    IMdiFullscreen: typeof import("~icons/mdi/fullscreen")["default"];
    IMdiFullscreenExit: typeof import("~icons/mdi/fullscreen-exit")["default"];
    IMdiQqchat: typeof import("~icons/mdi/qqchat")["default"];
    IMdiWeatherNight: typeof import("~icons/mdi/weather-night")["default"];
    IMdiWechat: typeof import("~icons/mdi/wechat")["default"];
    IMdiWhiteBalanceSunny: typeof import("~icons/mdi/white-balance-sunny")["default"];
    Loading: typeof import("element-plus/es")["ElLoadingDirective"];
    Panel: typeof import("./src/components/Panel.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchFilter: typeof import("./src/components/SearchFilter.vue")["default"];
    SlotComp: typeof import("./src/components/SlotComp.vue")["default"];
    VeeValidateError: typeof import("./src/components/VeeValidateError.vue")["default"];
    WangEditor: typeof import("./src/components/WangEditor.vue")["default"];
  }
}

export {};
