// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AsyncSelect: typeof import("./../src/components/AsyncSelect.vue")["default"];
    Card: typeof import("./../src/components/Card.vue")["default"];
    CForm: typeof import("./../src/components/CForm.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDescriptions: typeof import("element-plus/es")["ElDescriptions"];
    ElDescriptionsItem: typeof import("element-plus/es")["ElDescriptionsItem"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopconfirm: typeof import("element-plus/es")["ElPopconfirm"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSpace: typeof import("element-plus/es")["ElSpace"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTimeline: typeof import("element-plus/es")["ElTimeline"];
    ElTimelineItem: typeof import("element-plus/es")["ElTimelineItem"];
    EmptyBlock: typeof import("./../src/components/EmptyBlock.vue")["default"];
    IMdiAppleIcloud: typeof import("~icons/mdi/apple-icloud")["default"];
    IMdiArrowDownDropCircleOutline: typeof import("~icons/mdi/arrow-down-drop-circle-outline")["default"];
    IMdiArrowUpDropCircleOutline: typeof import("~icons/mdi/arrow-up-drop-circle-outline")["default"];
    IMdiFormatIndentDecrease: typeof import("~icons/mdi/format-indent-decrease")["default"];
    IMdiFullscreen: typeof import("~icons/mdi/fullscreen")["default"];
    IMdiFullscreenExit: typeof import("~icons/mdi/fullscreen-exit")["default"];
    IMdiGoogleTranslate: typeof import("~icons/mdi/google-translate")["default"];
    IMdiQqchat: typeof import("~icons/mdi/qqchat")["default"];
    IMdiRefresh: typeof import("~icons/mdi/refresh")["default"];
    IMdiTrendingDown: typeof import("~icons/mdi/trending-down")["default"];
    IMdiTrendingUp: typeof import("~icons/mdi/trending-up")["default"];
    IMdiWeatherNight: typeof import("~icons/mdi/weather-night")["default"];
    IMdiWechat: typeof import("~icons/mdi/wechat")["default"];
    IMdiWhiteBalanceSunny: typeof import("~icons/mdi/white-balance-sunny")["default"];
    Panel: typeof import("./../src/components/Panel.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchFilter: typeof import("./../src/components/SearchFilter.vue")["default"];
    TableSrcComponentsTableHead: typeof import("./../src/components/Table/src/components/TableHead.vue")["default"];
    TableSrcComponentsTableOption: typeof import("./../src/components/Table/src/components/TableOption.vue")["default"];
    TableSrcTable: typeof import("./../src/components/Table/src/Table.vue")["default"];
    ThemeBlock: typeof import("./../src/components/ThemeBlock.vue")["default"];
    VeeValidateError: typeof import("./../src/components/veeValidateError.vue")["default"];
    WangEditor: typeof import("./../src/components/WangEditor.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
  }
}
